### ISSUE TITLE
Memory usage growing

### ISSUE THREAD

**Issue by SzotsGabor** [kurt1288/KhepriChess#13]
Using the exe in analysis mode the allocated memory seems to grow all the time. Started with 197 MB, then I stopped it when it reached 1700.

**Comment by kurt1288** [comment]
Which binary did you see this with? What was time control?

**Comment by kurt1288** [comment]
>in analysis mode

Sorry, but I'm not sure what you mean by this. Were you running a UCI command to just have it analyze the position or was it something else?

**Comment by kurt1288** [comment]
After some debugging, I think this is caused by the hash table. I would be curious to know if you're changing the hash table size (and to what), but I have been able to see the memory usage get high even with just the default size (32MB). In the testing I've done, it seems like once the table is full the memory usage stops climbing.

So I don't think this is a memory leak issue (unless you are seeing something else). I think this is really just an issue with how JS is allocating memory for the table objects. While the table ends up using way more memory than it should, the number of objects in the table still appears to be correctly limited based on what the size *should* be.

I'll look into better ways of doing the hash table.

**Comment by SzotsGabor** [comment]
This was using the kheprichess_4.0.0-win.exe binary under Arena, hash set to 256 MB, starting position, analysis mode.

After 20 minutes of analyzing the memory growth decelerated and seemed to saturate at about 2 GB.

**Comment by SzotsGabor** [comment]
I have started a tournament with the TC 2mins+1seconds and memory usage does not exceed 700 MB during most games. This is an i7-12700K CPU running at 3.6 GHz.
Perhaps that could be tolerated if the hash size actually used did not exceed the intended 256 MB.

BTW, java has a command line option of -Xmx1024m which, AFAIK, limits its memory allocation. Can node not do the same?

**Comment by kurt1288** [comment]
Thanks for the additional info.

>Perhaps that could be tolerated if the hash size actually used did not exceed the intended 256 MB.

As far as I can tell, the actual number of hash entries is not exceeding the set amount. The memory is obviously going way beyond the set amount, but the number of entries doesn't appear to be.

>BTW, java has a command line option of -Xmx1024m which, AFAIK, limits its memory allocation. Can node not do the same?

I believe node does (a command line option). I have no idea if that would work here, since using it would end up capping the number hash entries.

I should be able to come up with a better solution in code.

**Comment by kurt1288** [comment]
v4.0.1 should have much better memory usage. If you still see issues, please let me know.
